const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.List,
		C3.Plugins.Button,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Shape3D,
		C3.Plugins.AJAX,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.List.Cnds.CompareSelection,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.AJAX.Exps.LastStatusCode,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{SelfDescribed: 0},
	{Text: 0},
	{AgeRange: 0},
	{Start: 0},
	{Cost: 0},
	{isSelected: 0},
	{card_id: 0},
	{card1pro: 0},
	{Card1: 0},
	{Card2: 0},
	{Card3: 0},
	{Card4: 0},
	{Text2: 0},
	{LetsGo: 0},
	{BudgetAvailable: 0},
	{Touch: 0},
	{Mouse: 0},
	{Confirm: 0},
	{Text3: 0},
	{bea0a22082f943f497df368d13c: 0},
	{Preview: 0},
	{pros: 0},
	{Text5: 0},
	{ERBedsCr: 0},
	{cons: 0},
	{Text4: 0},
	{"3DShape": 0},
	{Gender: 0},
	{CareerStage: 0},
	{Consent: 0},
	{debug: 0},
	{AJAX: 0},
	{Text6: 0},
	{AJAXTest: 0},
	{AJAXReturn: 0},
	{Text7: 0},
	{Age: 0},
	{GETString: 0},
	{Money: 0},
	{conSummary: 0},
	{proSummary: 0},
	{selectionMade: 0},
	{Round1: 0},
	{Round2: 0},
	{Round3: 0},
	{Round4: 0},
	{Round5: 0},
	{Round6: 0},
	{Round7: 0},
	{Money3: 0}
];

self.InstanceType = {
	SelfDescribed: class extends self.ITextInputInstance {},
	Text: class extends self.ITextInstance {},
	AgeRange: class extends self.IListInstance {},
	Start: class extends self.IButtonInstance {},
	Card1: class extends self.ISpriteInstance {},
	Card2: class extends self.ISpriteInstance {},
	Card3: class extends self.ISpriteInstance {},
	Card4: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	LetsGo: class extends self.IButtonInstance {},
	BudgetAvailable: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Confirm: class extends self.IButtonInstance {},
	Text3: class extends self.ITextInstance {},
	bea0a22082f943f497df368d13c: class extends self.ISpriteInstance {},
	Preview: class extends self.ISpriteInstance {},
	pros: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	ERBedsCr: class extends self.ISpriteInstance {},
	cons: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Gender: class extends self.IListInstance {},
	CareerStage: class extends self.IListInstance {},
	Consent: class extends self.IListInstance {},
	debug: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Text6: class extends self.ITextInstance {},
	AJAXTest: class extends self.IButtonInstance {},
	AJAXReturn: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {}
}